//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 12:44:35 AM CEST 
//


package pl.coderstrust.service.soap.bindingClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.coderstrust.service.soap.bindingClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.coderstrust.service.soap.bindingClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvoiceGetByIdResponse }
     * 
     */
    public InvoiceGetByIdResponse createInvoiceGetByIdResponse() {
        return new InvoiceGetByIdResponse();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link InvoiceGetByDateResponse }
     * 
     */
    public InvoiceGetByDateResponse createInvoiceGetByDateResponse() {
        return new InvoiceGetByDateResponse();
    }

    /**
     * Create an instance of {@link InvoiceList }
     * 
     */
    public InvoiceList createInvoiceList() {
        return new InvoiceList();
    }

    /**
     * Create an instance of {@link InvoiceGetByDateRequest }
     * 
     */
    public InvoiceGetByDateRequest createInvoiceGetByDateRequest() {
        return new InvoiceGetByDateRequest();
    }

    /**
     * Create an instance of {@link InvoiceGetByIdRequest }
     * 
     */
    public InvoiceGetByIdRequest createInvoiceGetByIdRequest() {
        return new InvoiceGetByIdRequest();
    }

    /**
     * Create an instance of {@link InvoiceRemoveRequest }
     * 
     */
    public InvoiceRemoveRequest createInvoiceRemoveRequest() {
        return new InvoiceRemoveRequest();
    }

    /**
     * Create an instance of {@link InvoiceUpdateResponse }
     * 
     */
    public InvoiceUpdateResponse createInvoiceUpdateResponse() {
        return new InvoiceUpdateResponse();
    }

    /**
     * Create an instance of {@link InvoiceUpdateRequest }
     * 
     */
    public InvoiceUpdateRequest createInvoiceUpdateRequest() {
        return new InvoiceUpdateRequest();
    }

    /**
     * Create an instance of {@link InvoiceRemoveResponse }
     * 
     */
    public InvoiceRemoveResponse createInvoiceRemoveResponse() {
        return new InvoiceRemoveResponse();
    }

    /**
     * Create an instance of {@link InvoiceAddRequest }
     * 
     */
    public InvoiceAddRequest createInvoiceAddRequest() {
        return new InvoiceAddRequest();
    }

    /**
     * Create an instance of {@link InvoiceAddResponse }
     * 
     */
    public InvoiceAddResponse createInvoiceAddResponse() {
        return new InvoiceAddResponse();
    }

    /**
     * Create an instance of {@link InvoiceEntry }
     * 
     */
    public InvoiceEntry createInvoiceEntry() {
        return new InvoiceEntry();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

}
