//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.23 at 12:44:35 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://invoice-service.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.coderstrust.service.soap.bindingClasses;
